[package]
name        = "flix-basic-duckdb"
description = "A database interface for Flix to DuckDB."
version     = "0.3.0"
flix        = "0.67.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

[dependencies]
"github:stephentetley/flix-pretty" = { version = "0.9.2", security = "unrestricted" }


[mvn-dependencies]
"org.duckdb:duckdb_jdbc" = "1.4.2.0"
